name: E-Commerce Application

on:
    push:
        branches: [main, master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm ci
              working-directory: advanced_e_commerce_ui
            - name: Print debugging information
              run: |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "Working Dictionary: $(pwd)"
                echo "Contents of Working Directory: $(ls -l)"
                echo "Contents of node_modules: $(ls -l node_modules)"
              working-directory: advanced_e_commerce_ui
    test:
      needs: build # build must succeed before testing
      runs-on: ubuntu-latest

      steps: 
          - name: check out code
            uses: actions/checkout@v2

          - name: use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20'
          
          - name: Install dependencies
            run: npm ci
            working-directory: advanced_e_commerce_ui

          - name: Run Tests
            run: npm test
            working-directory: advanced_e_commerce_ui
    deploy:
        needs: test #tests must succeed before deploying
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '20'
        - name: Install Dependencies
          run: npm install
          working-directory: advanced_e_commerce_ui
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
          working-directory: advanced_e_commerce_ui
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=preview --token=${{ secrets.E_COMMERCE_TOKEN }}
          working-directory: advanced_e_commerce_ui
        - name: Build Project Artifacts
          run: vercel build --token=${{ secrets.E_COMMERCE_TOKEN }}
          working-directory: advanced_e_commerce_ui
        - name: Deploy Project Artifacts to Vercel
          run: vercel deploy --prebuilt --token=${{ secrets.E_COMMERCE_TOKEN }}
          working-directory: advanced_e_commerce_ui